prtrej: added rejected dir verification

diff --git a/prt-utils/prtrej b/prt-utils/prtrej
--- a/prt-utils/prtrej
+++ b/prt-utils/prtrej
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: prtrej,v 1.2 2003/09/29 11:47:33 opel Exp $
+# $Id: prtrej,v 1.3 2004/02/05 01:25:27 sip Exp $
 # (c) 2003 by Martin Opel <mo@obbl-net.de>
 # (c) 2002 by Markus Ackermann <maol@symlink.ch>
 #
@@ -31,6 +31,12 @@ interrupted() {
 trap "interrupted" SIGHUP SIGINT SIGQUIT SIGTERM
 
 count=0
+
+if [ ! -d "$REJ" ]; then
+  echo "$REJ not found. Exiting"
+  exit 1
+fi
+
 for reject in `find /var/lib/pkg/rejected -type f`; do
     real="`echo $reject | sed -e 's#^/var/lib/pkg/rejected##'`"
     if diff $real $reject >/dev/null; then
